### ISSUE TITLE
Crash: EntityTippedArrow cannot be cast to EntityPlayer

### ISSUE THREAD

**Issue by genandnic** [DeflatedPickle/Heart-Drops#1]
The game crashes when I kill a mob using a bow. I'm using the most recent version of HeartDrops and AutoRegLib, with no other mods installed.

`[08:00:46] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:771) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.ClassCastException: net.minecraft.entity.projectile.EntityTippedArrow cannot be cast to net.minecraft.entity.player.EntityPlayer
	at com.deflatedpickle.heartdrops.events.ForgeEventHandler.onLivingDeathEvent(ForgeEventHandler.scala:48) ~[ForgeEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_620_ForgeEventHandler_onLivingDeathEvent_LivingDeathEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:585) ~[ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1159) ~[vp.class:?]
	at net.minecraft.entity.monster.EntityZombie.func_70645_a(EntityZombie.java:546) ~[adt.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1014) ~[vp.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:70) ~[ade.class:?]
	at net.minecraft.entity.monster.EntityZombie.func_70097_a(EntityZombie.java:233) ~[adt.class:?]
	at net.minecraft.entity.projectile.EntityArrow.func_184549_a(EntityArrow.java:369) ~[aeh.class:?]
	at net.minecraft.entity.projectile.EntityArrow.func_70071_h_(EntityArrow.java:267) ~[aeh.class:?]
	at net.minecraft.entity.projectile.EntityTippedArrow.func_70071_h_(SourceFile:98) ~[afa.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1990) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831) ~[oo.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1952) ~[amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1756) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765) ~[MinecraftServer.class:?]
	... 4 more`

**Comment by Xaikii** [comment]
Yep, same issue here
I did some more testing with this issues with other mods.

It seems to happen always when a mob is dying from something else than the Player (with exception of lava)
I tested it with:
Fire = Crash (on Fire Tick)
Lava = Normal
Fire Arrows = Crash (on Fire Tick)
Arrows = Normal
Wither Arrows = Crash (on Wither Tick)
Any Weapon = Normal
Wither = Crash (on Wither Tick)
Cinder(tamed Lycanite Mob) = Crash (on Fire Tick)

I think it got some problems to find the killer

**Comment by Jophire** [comment]
Time: 4/23/18 4:35 PM
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.entity.projectile.EntityLargeFireball cannot be cast to net.minecraft.entity.player.EntityPlayer
	at com.deflatedpickle.heartdrops.events.ForgeEventHandler.onLivingDeathEvent(ForgeEventHandler.scala:48)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1161_ForgeEventHandler_onLivingDeathEvent_LivingDeathEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:600)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1159)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1014)
	at net.minecraft.entity.monster.EntityGhast.func_70097_a(SourceFile:89)
	at net.minecraft.entity.projectile.EntityLargeFireball.func_70227_a(EntityLargeFireball.java:39)
	at net.minecraft.entity.projectile.EntityFireball.func_70071_h_(EntityFireball.java:98)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

Same bug most likely.

I shot a Ghasts fireball back at them with a vanilla arrow and bow.

**Comment by DeflatedPickle** [comment]
This bug should be fixed now, it was due to a silly mistake in the looting update.
